name: Build, Test, SonarCloud, DAST Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    name: Build + Test + SonarCloud + ZAP
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - run: |
          pip install coverage flask requests

      # Step 4: Run Unit Tests with Coverage
      - name: Run Unit Tests
        run: |
          coverage run -m unittest discover -s src -p "test_*.py"
          coverage xml

      # Step 5: Start the Python app in the background
      - name: Start App
        run: |
          nohup python src/main.py &
          sleep 5  # wait for the app to start

      # Step 6: SonarCloud Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.projectKey=navyavelicheti10_PythonScript
            -Dsonar.organization=navyavelicheti10
            -Dsonar.sources=src
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Step 7: OWASP ZAP DAST Scan
      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://localhost:8000'
          format: 'xml'
          output: 'zap-report.xml'
